### ISSUE TITLE
Huiswerk

### ISSUE THREAD

**Issue by TuriGuilano** [sasjakoning/blok-tech-2022#1]
Hi,

Maak een app.js in de root van je mapje aan (hoogste niveau)
run in je terminal - in je map van block-tech-2022; 

```bash
npm init --Y
```

installeer daarna express;
```bash
npm install express --save
```

vervolgens in je app.js een base server opzetten - zie docs; https://expressjs.com/en/starter/hello-world.html

**Comment by sasjakoning** [comment]
Hoi hoi, in principe heb ik dit soort dingen al gedaan. Ik heb verschillende branches waarin ik experimenteer met Express om bijv. users op te slaan of om een login system te maken (niet af gemaakt maar wel goed mee kunnen oefenen.) ook ben ik al een beetje aan het spelen met de database en doe ik momenteel onderzoek naar Gulp.

Maakt het trouwens uit hoe de .js heet waar express in staat?  Ik heb het bijv in een server.js gedaan of script.js.

**Comment by TuriGuilano** [comment]
Oh snap - ik had niet gedacht dat er al studenten zouden zijn die branches zouden maken, legend!
Geef wel even aan welke branch je main is (waar alles samenkomt zegmaar) dan kijk ik die na. BTW; je folder structure;

src/
server.js
public/
  /js
  /css
/helpers

verder maakt de naam niet zo veel uit - server of app.js is doorgaans. Pas wel je script in je package.json hierop aan.

Sick!

**Comment by sasjakoning** [comment]
top, dankjewel!
